### ISSUE TITLE
Error: Cannot find module 'rsvp'

### ISSUE THREAD

**Issue by vishsid73** [derickbailey/mustbe#11]
Hi,

I am having trouble at npm start. I am facing 

    > mustbe-demo@0.0.0 start /Users/siddharthsrivastava/Documents/sites/express/mustbe/demo
    > node ./bin/www

    module.js:338
    throw err;
          ^
    Error: Cannot find module 'rsvp'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/siddharthsrivastava/Documents/sites/express/mustbe/mustbe/verifier/index.js:1:74)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

    npm ERR! Darwin 14.3.0 
    npm ERR! argv "node" "/usr/local/bin/npm" "start"
    npm ERR! node v0.12.4
    npm ERR! npm  v2.10.1
    npm ERR! code ELIFECYCLE
    npm ERR! mustbe-demo@0.0.0 start: `node ./bin/www`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the mustbe-demo@0.0.0 start script 'node ./bin/www'.
    npm ERR! This is most likely a problem with the mustbe-demo package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node ./bin/www
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls mustbe-demo
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/siddharthsrivastava/Documents/sites/express/mustbe/demo/npm-debug.log

I tried installing rsvp module (npm install rsvp) but nothing. Also, tried clearing npm cache then also same.

Please guide.

**Comment by jinzhichen** [comment]
stuck into the same issue..

**Comment by cymen** [comment]
You need to run `npm install` in the root directory *and* in the demo directory!

**Comment by cleechtech** [comment]
@cymen gave the answer. This issue can be closed.

**Comment by derickbailey** [comment]
oh, sorry! i don't know how i missed this conversation until just now... yeah, npm install in the demo directory. i'll see about getting the readme updated with that info.
